# Generated by Django 5.0 on 2023-12-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='coverImage',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='plain_text',
            field=models.URLField(default=''),
        ),
    ]
