# Generated by Django 5.0 on 2023-12-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_book_coverimage_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='data_title_c948d2_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='data_name_b1d26c_idx'),
        ),
    ]
