# Generated by Django 5.0 on 2024-01-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_book_title_book_mygutenberg_title_c948d2_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='book',
            new_name='data_book_title_9ade21_idx',
            old_name='data_title_c948d2_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='data_person_name_7dd645_idx',
            old_name='data_name_b1d26c_idx',
        ),
    ]
