# Generated by Django 5.0 on 2024-01-23 23:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data",
            "0004_rename_data_title_c948d2_idx_data_book_title_9ade21_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphJaccard",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                (
                    "neighboor",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(), blank=True, size=None
                    ),
                ),
            ],
        ),
    ]
