# Generated by Django 5.0 on 2024-01-24 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_graphjaccard"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GraphJaccard",
        ),
    ]
