# Generated by Django 4.2.9 on 2024-01-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0009_keywordbookenglish_keywordbookfrench_keywordsenglish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neighbors",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="neighbors_as_book",
                to="data.book",
            ),
        ),
    ]
