# Generated by Django 5.1.6 on 2025-03-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_remove_book_language_book_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordbookenglish',
            name='tfidf_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='keywordbookfrench',
            name='tfidf_score',
            field=models.FloatField(default=0.0),
        ),
    ]
