# Generated by Django 5.1.6 on 2025-11-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_keywordbookenglish_tfidf_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Neighbors',
        ),
    ]
